# Generated by Django 4.2 on 2023-05-12 13:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_driver_total_paid_driver_total_pending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='rideId',
            field=models.CharField(default=api.models.generate_unique_code_for_rideid, max_length=10, unique=True),
        ),
    ]
