# Generated by Django 4.2 on 2023-06-23 09:14

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20230623_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxidetail',
            name='driver_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='api.newdriver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newdriver',
            name='driver_id',
            field=models.IntegerField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newridedetail',
            name='driver_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.newdriver'),
        ),
        migrations.AlterField(
            model_name='newridedetail',
            name='rideId',
            field=models.IntegerField(default=api.models.unique_generator.generate_unique_code_for_rideid, max_length=10, primary_key=True, serialize=False),
        ),
    ]
