# Generated by Django 4.2 on 2023-06-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_taxidetail_driver_id_alter_newdriver_driver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdriver',
            name='driver_id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
