# Generated by Django 4.2 on 2023-06-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_newdriver_driver_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newridedetail',
            name='driver_name',
        ),
    ]
