# Generated by Django 4.2 on 2023-06-23 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_newridedetail_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newridedetail',
            name='driver_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.newdriver'),
        ),
        migrations.AlterField(
            model_name='newridedetail',
            name='status',
            field=models.CharField(default='requested', max_length=20),
        ),
    ]
