# Generated by Django 4.2 on 2023-06-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_newridedetail_expecteddriverpay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newridedetail',
            name='driver_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
