# Generated by Django 4.2 on 2023-06-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_newdriver_driver_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdriver',
            name='driver_dob',
            field=models.DateField(default='2002-10-18', max_length=12),
            preserve_default=False,
        ),
    ]
