# Generated by Django 4.2 on 2023-06-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_newdriver_driver_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdriver',
            name='driver_phone',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
