version: "3"
services:
  frontend:
    build:
      context: ./Front-end
    expose:
      - 5173
    volumes:
      - ./Front-end:/app
    networks:
      mynetwork:
        ipv4_address: 172.18.0.6
  database:
    image: mysql:latest
    command: --skip-initialize-insecure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: taxioffice
      MYSQL_USER: django
      MYSQL_PASSWORD: password
    networks:
      mynetwork:
        ipv4_address: 172.18.0.8
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    networks:
      mynetwork:
        ipv4_address: 172.18.0.10
  backend:
    build:
      context: ./Back-end
    expose:
      - 8000
    volumes:
      - ./Back-end:/app
    depends_on:
      database:
        condition: service_healthy
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=taxioffice
      - MYSQL_USER=django
      - MYSQL_PASSWORD=password
    networks:
      mynetwork:
        ipv4_address: 172.18.0.7
networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.18.0.0/24
volumes:
  db_data:
